namespace: srs-cluster

bases:
  - origin
  - edge
  - backup

configMapGenerator:
  - name: sidecar-env
    literals:
      - redis_host=127.0.0.1
      - redis_port=6379
      - redis_master=mymaster
      - redis_pass=
      - redis_database=0
      - redis_pool_min=3
      - redis_pool_max=10

      - minio_endpoint=play.min.io
      - minio_port=80
      - minio_accessKey=
      - minio_secretKey=
      - minio_use_ssl=false
      - minio_bucketName=
      - minio_bucketPrefix=

      - DEFAULT_ADMIN_PASSWORD=

generatorOptions:
  disableNameSuffixHash: true

resources:
  - rbac.yaml
  - sample.yaml
