namespace: srs-cluster

bases:
  - origin
  - edge
  - backup

configMapGenerator:
  - name: sidecar-env
    literals:
      - redis_sentinel_host=127.0.0.1
      - redis_sentinel_port=26379
      - redis_name=mymaster
      - redis_pass=
      - redis_database=0
      - redis_pool_min=3
      - redis_pool_max=10

      - minio_endpoint=play.min.io
      - minio_port=80
      - minio_accessKey=
      - minio_secretKey=
      - minio_use_ssl=false
      - minio_bucketName=
      - minio_bucketPrefix=

      - SRS_API_SERVER=127.0.0.1:1985
      - SRS_CONF_FILE=./conf/srs.conf
      - SRS_HLS_PATH=./public
      - SRS_HLS_EXPIRE=60
      - SRS_PROXY_HOST=127.0.0.1:8080

      - DEFAULT_ADMIN_PASSWORD=
      - DEFAULT_TOKEN_EXPIRE=60

      - OSS_BACKUP_ENABLED=false

generatorOptions:
  disableNameSuffixHash: true

resources:
  - rbac.yaml