version: "3"

services:
  origin:
    image: hub.bigdatagz.com/ossrs/srs:v4.0
    restart: always
    networks:
      - overlay
    ports:
      - 19350:1935

  origin-sidecar:
    image: hub.bigdatagz.com/ossrs/srs-sidecar:latest
    restart: always
    env_file:
      - sidecar-env
    volumes:
      - ./conf/origin.conf:/app/conf/srs.conf
    networks:
      - overlay
    command:
      - --mode
      - origin
      - --srs-api-server
      - origin:1985
    depends_on:
      - origin
      - redis

  backup:
    image: hub.bigdatagz.com/ossrs/srs:v4.0
    restart: always
    volumes:
      - hls-data:/usr/local/srs/objs/nginx/html
    networks:
      - overlay

  backup-sidecar:
    image: hub.bigdatagz.com/ossrs/srs-sidecar:latest
    restart: always
    env_file:
      - sidecar-env
    volumes:
      - ./conf/backup.conf:/app/conf/srs.conf
      - hls-data:/app/public
    networks:
      - overlay
    command:
      - --mode
      - origin
      - --srs-api-server
      - backup:1985
    depends_on:
      - backup
      - redis

  edge:
    image: hub.bigdatagz.com/ossrs/srs:v4.0
    restart: always
    networks:
      - overlay
    ports:
      - 1935:1935

  edge-sidecar:
    image: hub.bigdatagz.com/ossrs/srs-sidecar:latest
    restart: always
    env_file:
      - sidecar-env
    volumes:
      - ./conf/edge.conf:/app/conf/srs.conf
    networks:
      - overlay
    command:
      - --srs-api-server
      - edge:1985
      - --srs-proxy-server
      - backup-sidecar:8080
    ports:
      - 8080:8080
    depends_on:
      - edge
      - redis

  redis:
    image: hub.bigdatagz.com/library/redis:5.0-alpine
    restart: always
    env_file:
      - sidecar-env
    volumes:
    - ./dump.rdb:/data/dump.rdb
    networks:
      - overlay
    command:
      - sh
      - -c
      - 'redis-server --requirepass $${redis_pass} --dbfilename dump.rdb'

  sample:
    image: hub.bigdatagz.com/ossrs/rtmp-push-sample:latest
    restart: always
    environment:
      - AUTH_SERVER=edge-sidecar:8080
      - RTMP_HOST=origin
      - RTMP_PORT=1935
      - RTMP_USER=admin
      - RTMP_PASSWORD=defaultpassword
    networks:
      - overlay
    depends_on:
      - origin
      - edge-sidecar

networks:
  overlay:

volumes:
  hls-data: