namePrefix: backup-

commonLabels:
  app: backup

resources:
  - statefulset.yaml
  - svc.yaml

configMapGenerator:
  - name: conf
    files:
      - srs.conf

generatorOptions:
  disableNameSuffixHash: true
