kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  clusterIP: None
  ports:
    - name: rtmp
      port: 1935
      targetPort: rtmp
    - name: sidecar
      port: 8080
      targetPort: sidecar
  selector:
    app: backup